# Porta e HTTPS
server.port=8443
server.ssl.key-store=classpath:meukeystore.p12
server.ssl.key-store-password=MINHA_SENHA123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=meualias

# DataSource H2 via TCP (externo)
spring.datasource.url=jdbc:h2:tcp://localhost:9092/./data/embalando
spring.datasource.username=sa
spring.datasource.password=

spring.datasource.driver-class-name=org.h2.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Console web H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
