# Porta padrão para a Railway
server.port=8080

# Configuração do MySQL da Railway (usando domínio público)
spring.datasource.url=jdbc:mysql://turntable.proxy.rlwy.net:49898/railway
spring.datasource.username=root
spring.datasource.password=WISYJXmVOGuNCGzWOPOLeitxPXFsAFDM
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
